version: "2.21"

services:
  healthcheck:
    image: healthcheck
    container_name: healthcheck
    build: .
    env_file:
      - .env

secrets:
  "ECHECS_FRANCE_RESULTS_API":
    file: .env
  "CHESS_PDF_API":
    file: .env
  "PORTFOLIO":
    file: .env  

